version: "3"


volumes:
  DB-tweetter-postgres:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - DB-tweetter-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
